### ISSUE TITLE
Boot a VM with a (good, old-fashioned) ISO in 5 seconds.

### ISSUE THREAD

**Issue by hosh** [jbenet/ipfs-container-demos#6]
1. Mount ipfs
2. boot from mount
## Discussion
1. This is probably more interesting as a demo if we were to find more obscure OSs to run. For example: Haiku (BeOS clone), Plan 9, one of the various Lisp machines.
2. Another interesting application for this is educational distros.

**Comment by jbenet** [comment]
- a prepated vm -- like `/ipfs/QmdTmSQtCz9D6vt2AbvQkYo3edFcTYoU7FDmDD7bPWDccA/ipfs.iso`
- this makefile https://gist.github.com/jbenet/76afa70955910a2ed097  
- virtualbox
