### ISSUE TITLE
Download a VM in 5 seconds.

### ISSUE THREAD

**Issue by hosh** [jbenet/ipfs-container-demos#7]
1. ipfs get the vm.
## Discussion

Building block for https://github.com/jbenet/ipfs-container-demos/issues/6

**Comment by jbenet** [comment]
we just need ipfs as is, and a prepared VM.

**Comment by hosh** [comment]
I'll use the set that opscode has built from bento to seed it.

**Comment by hosh** [comment]
See #12

May need to refine the demo later with scripts and such.

**Comment by hosh** [comment]
Further refinements needed.
